version: "3.9"

services:
  backend:
    image: gym-backend
    container_name: gym-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongo:27017/bodyfirst
      NODE_ENV: production
      REDIS_URI: redis://redis:6379
    depends_on:
      - mongo
    # volumes:
    #   - ./backend:/app
    #   - /app/node_modules
    command: npx nodemon src/index.ts

  frontend:
    image: gym-frontend
    container_name: gym-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8000
    # volumes:
    #   - ./frontend:/app
    # command: npm install && npm run dev

  mongo:
    image: mongo:6
    container_name: bodyfirst-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: bodyfirst-redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  mongo-data:
  grafana-data:
